#!/bin/env python
import h5py
import numpy as np
import sys

nomb = int(sys.argv[1])
chiloc = np.loadtxt('G2_uudd_1_2222')
nomv = int(np.sqrt(chiloc.shape[0]))



f = open('PARAMS','r')
norb = int(f.read().split('\n')[0])

g2_uu = np.zeros((nomv, nomv, norb,norb,norb,norb, nomb),dtype = complex)
g2_ud = np.zeros((nomv, nomv, norb,norb,norb,norb ,nomb),dtype = complex)


from itertools import product
for iom,i1,i2,i3,i4 in product(range(nomb),range(norb),range(norb),range(norb),range(norb)) :
    g2_1 = np.loadtxt('G2_uuuu_{}_{}{}{}{}'.format(iom+1,i1+1,i2+1,i3+1,i4+1)).T
    g2_2 = np.loadtxt('G2_uudd_{}_{}{}{}{}'.format(iom+1,i1+1,i2+1,i3+1,i4+1)).T
    g2_1 = g2_1[0] +1j* g2_1[1]
    g2_2 = g2_2[0] +1j* g2_2[1]
    k = 0

    for i in range(nomv) :
        for j in range(nomv) :
            g2_uu[i,j,i2,i1,i4,i3,iom] = g2_1[k]
            g2_ud[i,j,i2,i1,i4,i3,iom] = g2_2[k]
            k+=1

f = h5py.File('G2.h5', 'w')
f.create_dataset('g2_uuuu',data=g2_uu)
f.create_dataset('g2_uudd',data=g2_ud)
# f = h5py.File('chiS.h5', 'w')
# f.create_dataset('chis',data=g2_uu-g2_ud)
# f.create_dataset('chic',data=g2_uu+g2_ud)
# f.create_dataset('beta',data=[beta])
f.close()
